name: primeira-pipeline
on: #qual evento vai acontecer 
  push: #Push da branch em seguida especificar qual é a branch
    branches: ["main"]
  workflow_dispatch: #permite a execução da pipeline mannualmente
jobs: #as tarefas que serão executadas de acordo com a ordem declarada
  primeiro-job: 
    name: "Meu Job" #todo job precisa ser especificado o nome
    runs-on: ubuntu-latest # runs é o agente de execução
    steps: #os passos de execução nele que adicionamos as ações que serão tomadas
      - name: "Primeira ação"
        run: echo "Hellow Word" #comando que vai executar "run"
      - name: "Segunda ação"
        run: |
          echo "Você criou seu primeiro Worflow"
          echo "Parabéns"
      - name: "Script python" 
        run: |
          variavel = "Meu teste em Python"
          print (variavel)
        shell: python #especificae a linguagem do terminal usada
  segundo-job:
    name: "projeto em nodejs"
    runs-on: ubuntu-latest
    steps: 
      - name: "Verificação da versão atual do NODEJS"
        run: node --version
      - name: "Definindo a versão do NODEJS"
        uses: actions/setup-node@v6
        with:
          node-version: 'v25.2.1'
      - name: "Verificação da versão atual do NODEJS"
        run: node --version
